const web = {}
web.user = {}
web.sys = {}
web.app = {}
web.sys.srcs = {}
web.sys.srcs.adjustors = {}
web.sys.srcs.adjustors.effects = {}
web.sys.srcs.establishers = {}
web.sys.srcs.establishers.models = {}
web.sys.srcs.executors = {}
web.sys.srcs.protocols = {}
web.sys.srcs.protocols.layers = {}
web.sys.srcs.protocols.layers.applications = {}
web.sys.srcs.protocols.managers = {}
web.sys.srcs.protocols.models = {}
